cursor #e9e2d4
cursor_text_color #cec6b4

foreground            #e9e2d4
background            #16130b
selection_foreground  #383016
selection_background  #d3c6a1
url_color             #e0c56d

color0   #16130b
color1   #e14878
color2   #94d66e
color3   #dbb17b
color4   #a48728
color5   #a89762
color6   #e0c56d
color7   #abb2bf
color8   #5c6370
color9   #e05f8b
color10  #a6e086
color11  #e8c497
color12  #ecd388
color13  #99723e
color14  #837b3c
color15  #ffffff
