### Startup Apps & Services
exec /usr/libexec/lxqt-policykit-agent
exec mako
exec nm-applet --indicator
exec blueman-applet
exec gammastep
exec_always sh -c 'echo 1 | sudo tee /sys/devices/platform/asus-nb-wmi/fan_boost_mode > /dev/null && echo 1 > /tmp/fan_mode_state'
exec dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway GTK_THEME=Mint-Y-Dark
exec systemctl --user start sway-session.target
exec copyq
exec thunar --daemon
exec ~/.local/bin/battery-monitor.sh
exec ~/.local/bin/voice-dictate --daemon
exec ~/.local/bin/pomodoro-engine.sh start
exec ~/.local/bin/megasync &
exec ~/.local/bin/thunderbird &

exec swayidle -w \
    timeout 900 'swaylock -f' \
    timeout 1200 'systemctl suspend' \
    before-sleep 'swaylock -f'
