### Window Rules & Exceptions
for_window [app_id="scratchpad_term"] floating enable, resize set 900 600, move position center
for_window [app_id="flameshot"] border pixel 0, floating enable, fullscreen disable, move absolute position 0 0

# CopyQ floating rule
for_window [app_id="copyq"] floating enable
for_window [class="copyq"] floating enable

# Window Rules (Dialogs & Floating Popups)
for_window [app_id="blueman-manager"] floating enable, resize set 700 500, move position center
for_window [class="Blueman-manager"] floating enable, resize set 700 500, move position center
for_window [app_id="nm-connection-editor"] floating enable, resize set 700 500, move position center
for_window [class="Nm-connection-editor"] floating enable, resize set 700 500, move position center
for_window [app_id="pavucontrol"] floating enable, resize set 800 550, move position center
for_window [class="Pavucontrol"] floating enable, resize set 800 550, move position center
for_window [app_id="zenity"] floating enable, move position center
for_window [class="Zenity"] floating enable, move position center

# MEGAsync & Thunderbird Window Behavior
for_window [app_id="(?i)megasync"] floating enable, resize set 900 650, move position center
for_window [class="(?i)megasync"] floating enable, resize set 900 650, move position center
for_window [app_id="(?i)thunderbird"] floating disable
for_window [class="(?i)thunderbird"] floating disable

for_window [app_id="pl.skmedix.sklauncher"] floating enable, move position center
for_window [app_id="FastClient"] floating enable, move position center
for_window [app_id="thunar"] floating enable, move position center
for_window [app_id="kitty"] floating enable, move position center
for_window [app_id="md.obsidian.Obsidian"] floating enable, move position center
for_window [app_id="firefox-nightly"] floating enable, move position center
for_window [app_id="brave-browser"] floating enable, move position center
