# Windows XP Luna Classic Blue Terminal Palette
foreground            #FFFFFF
background            #0F2B5C
selection_foreground  #FFFFFF
selection_background  #3C7BF2

# Cursor
cursor                #549D34
cursor_text_color     #FFFFFF

# Black
color0 #16469C
color8 #2C6AE3

# Red
color1 #D13438
color9 #E81123

# Green
color2  #549D34
color10 #3DBA67

# Yellow
color3  #F1A80A
color11 #FFC83D

# Blue
color4  #0054E3
color12 #3880F5

# Magenta
color5  #9B51E0
color13 #F0719B

# Cyan
color6  #3A6EA5
color14 #7A96DF

# White
color7  #C5D6F5
color15 #FFFFFF
