# Steam UI / High-Contrast Dark Slate Palette for Kitty
foreground            #F0F6FC
background            #0D1117
selection_foreground  #FFFFFF
selection_background  #21262D

# Cursor
cursor                #58A6FF
cursor_text_color     #0D1117

# Black
color0 #161B22
color8 #30363D

# Red
color1 #F85149
color9 #FF7B72

# Green
color2  #39D353
color10 #56D364

# Yellow
color3  #D29922
color11 #E3B341

# Blue
color4  #3880F5
color12 #58A6FF

# Magenta
color5  #BC8CFF
color13 #D2A8FF

# Cyan
color6  #39C5CF
color14 #56D4DD

# White
color7  #B1BAC4
color15 #F0F6FC
