# Windows 7 Aero Glass Color Scheme for Kitty
foreground            #F8FAFC
background            #0F172A
selection_foreground  #FFFFFF
selection_background  #2563EB

# Cursor
cursor                #60A5FA
cursor_text_color     #0F172A

# Black
color0 #1E293B
color8 #334155

# Red
color1 #EF4444
color9 #F87171

# Green
color2  #22C55E
color10 #4ADE80

# Yellow
color3  #EAB308
color11 #FACC15

# Blue
color4  #3B82F6
color12 #60A5FA

# Magenta
color5  #A855F7
color13 #C084FC

# Cyan
color6  #06B6D4
color14 #22D3EE

# White
color7  #CBD5E1
color15 #F8FAFC
